name: Linters
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
permissions:
  contents: read
jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'

      - name: 'Run Linters Aggregator'
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          skip-go-installation: true
